import type { Question } from './types'

export const DEFAULT_QUESTIONS: Question[] = [
  { id: 'q-e-01', difficulty: 'easy', category: 'DSA-Arrays',
    question: 'What is printed?\nint a[] = {12, 7, 19, 5, 24};\nprintf("%d", a[2] - a[4]);',
    options: ['12', '-5', '5', '-12'],
    correctIndex: 1 },
  { id: 'q-e-02', difficulty: 'easy', category: 'DSA-Arrays',
    question: 'What is printed?\nint a[] = {2, 4, 6, 8};\nfor(int i = 0; i < 4; i += 2)\nprintf("%d ", a[i]);',
    options: ['2 4', '2 6', '4 8', '2 4 6 8'],
    correctIndex: 1 },
  { id: 'q-e-03', difficulty: 'easy', category: 'DSA-Arrays',
    question: 'What is the final value of a[1]?\nint a[] = {10, 20, 30};\na[1] = a[0] + a[2];',
    options: ['20', '30', '40', '50'],
    correctIndex: 2 },
  { id: 'q-e-04', difficulty: 'easy', category: 'DSA-Arrays',
    question: 'What is printed?\nint a[] = {10, 20, 30, 40};\nprintf("%d", 2[a]);',
    options: ['2', '20', '30', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-e-05', difficulty: 'easy', category: 'DSA-Stacks',
    question: 'A stack is initially empty.\npush(10)\npush(20)\npop()\npush(30)\nWhat is at the top?',
    options: ['10', '20', '30', 'Empty'],
    correctIndex: 2 },
  { id: 'q-e-06', difficulty: 'easy', category: 'DSA-Stacks',
    question: 'A stack contains 10, 20, 30, 40, where 40 is at the top.\nTwo pop() operations are performed, followed by push(50).\nWhat is the new top?',
    options: ['20', '30', '40', '50'],
    correctIndex: 3 },
  { id: 'q-e-07', difficulty: 'easy', category: 'DSA-Stacks',
    question: 'Which sequence of operations leaves 20 at the top?',
    options: ['push(10), push(20), push(30), pop()', 'push(10), push(20), pop()', 'push(20), push(10), pop()', 'push(10), pop(), push(20)'],
    correctIndex: 3 },
  { id: 'q-e-08', difficulty: 'easy', category: 'DSA-Stacks',
    question: 'A stack contains 10, 20, 30, with 30 at the top.\nWhat happens after: pop(), pop(), push(40)?',
    options: ['Top is 10', 'Top is 20', 'Top is 30', 'Top is 40'],
    correctIndex: 3 },
  { id: 'q-e-09', difficulty: 'easy', category: 'DSA-Queues',
    question: 'A queue contains 10 → 20 → 30, with 10 at the front.\nAfter one dequeue() and one enqueue(40), what is the queue?',
    options: ['10 20 30 40', '20 30 40', '20 30', '10 20 40'],
    correctIndex: 1 },
  { id: 'q-e-10', difficulty: 'easy', category: 'DSA-Queues',
    question: 'Which element leaves first from a normal queue?\n5 → 8 → 12 → 20, with 5 at the front.',
    options: ['5', '8', '12', '20'],
    correctIndex: 0 },
  { id: 'q-e-11', difficulty: 'easy', category: 'DSA-Queues',
    question: 'A queue initially contains 10, 20, 30.\nOperations: dequeue(), enqueue(40), dequeue()\nWhat remains?',
    options: ['10 40', '20 30', '30 40', '20 40'],
    correctIndex: 2 },
  { id: 'q-e-12', difficulty: 'easy', category: 'DSA-Recursion',
    question: 'What is printed?\nvoid fun(int n) {\nif(n == 0) return;\nprintf("%d ", n);\nfun(n - 1);\n}\nfun(4);',
    options: ['1 2 3 4', '4 3 2 1', '4 3 2 1 0', '0 1 2 3 4'],
    correctIndex: 1 },
  { id: 'q-e-13', difficulty: 'easy', category: 'DSA-Recursion',
    question: 'For fun(4), what is returned?\nint fun(int n) {\nif(n <= 1) return 1;\nreturn n * fun(n - 1);\n}',
    options: ['4', '8', '12', '24'],
    correctIndex: 3 },
  { id: 'q-e-14', difficulty: 'easy', category: 'DSA-Recursion',
    question: 'What is printed?\nvoid fun(int n) {\nif(n == 0) return;\nfun(n - 1);\nprintf("%d ", n);\n}\nfun(3);',
    options: ['3 2 1', '1 2 3', '3 1 2', '0 1 2 3'],
    correctIndex: 1 },
  { id: 'q-e-15', difficulty: 'easy', category: 'DSA-Basics',
    question: 'Which data structure is most naturally used to implement a browser\'s Back operation?',
    options: ['Queue', 'Stack', 'Array', 'Tree'],
    correctIndex: 1 },
  { id: 'q-e-16', difficulty: 'easy', category: 'C-Pointers',
    question: 'What is printed?\nint x = 25;\nint *p = &x;\n*p = 40;\nprintf("%d", x);',
    options: ['25', '40', 'Address of x', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-e-17', difficulty: 'easy', category: 'C-Pointers',
    question: 'What is printed?\nint a[] = {10, 20, 30, 40};\nint *p = a;\nprintf("%d", *(p + 2));',
    options: ['10', '20', '30', '40'],
    correctIndex: 2 },
  { id: 'q-e-18', difficulty: 'easy', category: 'C-Pointers',
    question: 'What is printed?\nint a = 10;\nint *p = &a;\n(*p)++;\nprintf("%d", a);',
    options: ['10', '11', '12', 'Address of a'],
    correctIndex: 1 },
  { id: 'q-e-19', difficulty: 'easy', category: 'C-Pointers',
    question: 'What is printed?\nint a[] = {10, 20, 30};\nint *p = a;\nprintf("%d", *p + 1);',
    options: ['10', '11', '20', '30'],
    correctIndex: 1 },
  { id: 'q-e-20', difficulty: 'easy', category: 'C-Pointers',
    question: 'What is printed?\nint a[] = {10, 20, 30};\nint *p = a;\nprintf("%d", *(p + 1) + 5);',
    options: ['15', '20', '25', '35'],
    correctIndex: 2 },
  { id: 'q-e-21', difficulty: 'easy', category: 'C-Basics',
    question: 'What is printed?\nvoid change(int a[]) { a[0] = 100; }\nint main() {\nint x[] = {10, 20};\nchange(x);\nprintf("%d", x[0]);\n}',
    options: ['10', '20', '100', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-e-22', difficulty: 'easy', category: 'C-Basics',
    question: 'Assume int occupies 4 bytes.\nint a[5];\nprintf("%zu", sizeof(a));',
    options: ['4', '5', '20', 'Depends on the values'],
    correctIndex: 2 },
  { id: 'q-e-23', difficulty: 'easy', category: 'C-Basics',
    question: 'What is printed?\nvoid fun(int x) { x = 50; }\nint main() {\nint a = 10;\nfun(a);\nprintf("%d", a);\n}',
    options: ['10', '50', '0', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-e-24', difficulty: 'easy', category: 'C-Basics',
    question: 'What is printed?\nvoid fun() {\nstatic int x = 0;\nx++;\nprintf("%d ", x);\n}\nfun();\nfun();\nfun();',
    options: ['1 1 1', '0 1 2', '1 2 3', '0 0 0'],
    correctIndex: 2 },
  { id: 'q-e-25', difficulty: 'easy', category: 'C-Structures',
    question: 'What is printed?\nstruct Student {\nint roll;\nint marks;\n};\nstruct Student s = {101, 85};\nprintf("%d", s.marks);',
    options: ['101', '85', '186', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-26', difficulty: 'easy', category: 'C-Structures',
    question: 'What is printed?\nstruct Student {\nint roll;\nint marks;\n};\nstruct Student s[2] = {{101, 80}, {102, 90}};\nprintf("%d", s[1].marks);',
    options: ['80', '90', '102', '170'],
    correctIndex: 1 },
  { id: 'q-e-27', difficulty: 'easy', category: 'C-Structures',
    question: 'What is printed?\nstruct Student { int marks; };\nstruct Student s = {90};\nstruct Student *p = &s;\nprintf("%d", p->marks);',
    options: ['Address of marks', '90', '0', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-e-28', difficulty: 'easy', category: 'C-Structures',
    question: 'Which expression accesses marks through a structure pointer p?',
    options: ['p.marks', 'p->marks', '*p.marks', '&p.marks'],
    correctIndex: 1 },
  { id: 'q-e-29', difficulty: 'easy', category: 'C-Preprocessor',
    question: 'What is printed?\n#define DOUBLE(x) x + x\nprintf("%d", DOUBLE(3) * 2);',
    options: ['6', '9', '12', '18'],
    correctIndex: 1 },
  { id: 'q-e-30', difficulty: 'easy', category: 'C-Preprocessor',
    question: 'Which statement is correct about #include <stdio.h>?',
    options: ['It creates a variable called stdio', 'It asks the preprocessor to include the header\'s contents', 'It executes the file at runtime', 'It defines a macro'],
    correctIndex: 1 },
  { id: 'q-e-31', difficulty: 'easy', category: 'Python-Lists',
    question: 'What is printed?\na = [1, 2, 3]\nb = a\nb[0] = 10\nprint(a)',
    options: ['[1, 2, 3]', '[10, 2, 3]', '[10]', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-32', difficulty: 'easy', category: 'Python-Lists',
    question: 'What is printed?\nx = [10, 20, 30, 40]\nprint(x[-2])',
    options: ['20', '30', '40', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-33', difficulty: 'easy', category: 'Python-Lists',
    question: 'What is printed?\nx = [10, 20, 30, 40, 50]\nprint(x[1:4])',
    options: ['[10, 20, 30]', '[20, 30, 40]', '[20, 30, 40, 50]', '[10, 20, 30, 40]'],
    correctIndex: 1 },
  { id: 'q-e-34', difficulty: 'easy', category: 'Python-Lists',
    question: 'What is printed?\nx = [10, 20, 30, 40, 50]\nprint(x[:3])',
    options: ['[10, 20]', '[10, 20, 30]', '[20, 30, 40]', '[10, 20, 30, 40]'],
    correctIndex: 1 },
  { id: 'q-e-35', difficulty: 'easy', category: 'Python-Loops',
    question: 'What is printed?\nfor i in range(2, 7, 2):\nprint(i, end=" ")',
    options: ['2 4 6', '2 4 6 8', '1 3 5 7', '2 3 4 5 6'],
    correctIndex: 0 },
  { id: 'q-e-36', difficulty: 'easy', category: 'Python-Loops',
    question: 'What is printed?\nfor i in range(3):\nprint(i)\nelse:\nprint("Done")',
    options: ['0 1 2', '0 1 2 Done', 'Done 0 1 2', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-37', difficulty: 'easy', category: 'Python-Loops',
    question: 'What is printed?\nfor i in range(5):\nif i == 2:\nbreak\nprint(i)\nelse:\nprint("Done")',
    options: ['0 1 Done', '0 1', '0 1 2 Done', 'Done'],
    correctIndex: 1 },
  { id: 'q-e-38', difficulty: 'easy', category: 'Python-Lists',
    question: 'What is printed?\nx = [10, 20, 30, 40]\nx.pop(1)\nprint(x)',
    options: ['[10, 30, 40]', '[20, 30, 40]', '[10, 20, 40]', '[10, 20, 30]'],
    correctIndex: 0 },
  { id: 'q-e-39', difficulty: 'easy', category: 'Python-Functions',
    question: 'What is printed?\ndef add(x, items=[]):\nitems.append(x)\nreturn items\nprint(add(1))\nprint(add(2))',
    options: ['[1] / [2]', '[1] / [1, 2]', '[1, 2] / [1, 2]', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-40', difficulty: 'easy', category: 'Python-Basics',
    question: 'Which statement is correct?',
    options: ['Tuples cannot contain lists', 'Tuples are generally immutable', 'Tuples can only contain numbers', 'Tuples cannot be indexed'],
    correctIndex: 1 },
  { id: 'q-e-41', difficulty: 'easy', category: 'Python-Dictionaries',
    question: 'What is printed?\nd = {"a": 10, "b": 20}\nd["a"] = 50\nprint(d["a"])',
    options: ['10', '20', '50', 'Error'],
    correctIndex: 2 },
  { id: 'q-e-42', difficulty: 'easy', category: 'Python-Basics',
    question: 'What is printed?\nx = []\nif x:\nprint("A")\nelse:\nprint("B")',
    options: ['A', 'B', '[]', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-43', difficulty: 'easy', category: 'Python-Basics',
    question: 'What is printed?\na = [1, 2]\nb = [1, 2]\nprint(a == b)',
    options: ['True', 'False', 'None', 'Error'],
    correctIndex: 0 },
  { id: 'q-e-44', difficulty: 'easy', category: 'Python-Basics',
    question: 'What does is primarily test?',
    options: ['Whether two values are equal', 'Whether two references refer to the same object', 'Whether two numbers are integers', 'Whether two lists have the same length'],
    correctIndex: 1 },
  { id: 'q-e-45', difficulty: 'easy', category: 'Python-Strings',
    question: 'What is printed?\ns = "PYTHON"\nprint(s[1:5])',
    options: ['PYTH', 'YTHO', 'YTH', 'THON'],
    correctIndex: 1 },
  { id: 'q-e-46', difficulty: 'easy', category: 'Java-Classes-Objects',
    question: 'class Student {\nint marks = 80;\n}\nStudent s = new Student();\nSystem.out.println(s.marks);\nWhat is printed?',
    options: ['0', '80', 'Student', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-e-47', difficulty: 'easy', category: 'Java-Constructors',
    question: 'class Student {\nStudent() {\nSystem.out.println("Created");\n}\n}\nStudent s = new Student();\nWhat is printed?',
    options: ['Nothing', 'Student', 'Created', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-e-48', difficulty: 'easy', category: 'Java-Constructors',
    question: 'Which statement about a constructor is correct?',
    options: ['It must have the same name as the class', 'It must have a return type', 'It must be static', 'It can have any name'],
    correctIndex: 0 },
  { id: 'q-e-49', difficulty: 'easy', category: 'Java-Basics',
    question: 'class Student {\nint marks;\nStudent(int marks) {\nthis.marks = marks;\n}\n}\nWhat does this.marks refer to?',
    options: ['The constructor parameter', 'The object\'s marks variable', 'A static variable', 'A new variable'],
    correctIndex: 1 },
  { id: 'q-e-50', difficulty: 'easy', category: 'Java-Encapsulation',
    question: 'A class keeps its data members private and provides public methods to access or modify them.\nWhich OOP concept is this?',
    options: ['Inheritance', 'Encapsulation', 'Polymorphism', 'Recursion'],
    correctIndex: 1 },
  { id: 'q-e-51', difficulty: 'easy', category: 'Java-Encapsulation',
    question: 'class Student {\nprivate int marks = 90;\n}\nStudent s = new Student();\nSystem.out.println(s.marks);\nWhat happens?',
    options: ['Prints 90', 'Prints 0', 'Compilation error', 'Prints private'],
    correctIndex: 2 },
  { id: 'q-e-52', difficulty: 'easy', category: 'Java-Inheritance',
    question: 'class Animal {\nvoid eat() {\nSystem.out.println("Eating");\n}\n}\nclass Dog extends Animal {\n}\nWhich statement is true?',
    options: ['Dog cannot use eat()', 'Dog inherits eat()', 'Animal inherits from Dog', 'extends creates an object'],
    correctIndex: 1 },
  { id: 'q-e-53', difficulty: 'easy', category: 'Java-Polymorphism',
    question: 'Which is valid method overloading?',
    options: ['void add(int a)', 'void add(int a)', 'void add(int a)', 'void add()'],
    correctIndex: 0 },
  { id: 'q-e-54', difficulty: 'easy', category: 'Java-Polymorphism',
    question: 'int add(int a, int b)\ndouble add(int a, int b)\nCan these two methods exist in the same class as overloaded methods?',
    options: ['Yes', 'No, because only the return type is different', 'Yes, if double is larger', 'Only if both are static'],
    correctIndex: 1 },
  { id: 'q-e-55', difficulty: 'easy', category: 'Java-Inheritance',
    question: 'class Animal {\nvoid sound() {\nSystem.out.println("Animal");\n}\n}\nclass Dog extends Animal {\nvoid sound() {\nSystem.out.println("Dog");\n}\n}\nDog d = new Dog();\nd.sound();\nWhat is printed?',
    options: ['Animal', 'Dog', 'Animal Dog', 'Error'],
    correctIndex: 1 },
  { id: 'q-e-56', difficulty: 'easy', category: 'Java-Polymorphism',
    question: 'Animal a = new Dog();\na.sound();\nIf Dog overrides sound(), which implementation runs?',
    options: ['Animal\'s', 'Dog\'s', 'Both', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-e-57', difficulty: 'easy', category: 'Java-Inheritance',
    question: 'If a child class wants to call a method from its parent class, which keyword can it use?',
    options: ['this', 'parent', 'super', 'base'],
    correctIndex: 2 },
  { id: 'q-e-58', difficulty: 'easy', category: 'Java-Basics',
    question: 'class Test {\nstatic int count = 10;\n}\nSystem.out.println(Test.count);\nWhat is printed?',
    options: ['0', '10', 'count', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-e-59', difficulty: 'easy', category: 'Java-Static',
    question: 'class Test {\nstatic int count = 0;\nTest() {\ncount++;\n}\n}\nnew Test();\nnew Test();\nnew Test();\nSystem.out.println(Test.count);',
    options: ['0', '1', '2', '3'],
    correctIndex: 3 },
  { id: 'q-e-60', difficulty: 'easy', category: 'Java-Polymorphism',
    question: 'class Vehicle {\nvoid move() {\nSystem.out.println("Vehicle");\n}\n}\nclass Car extends Vehicle {\nvoid move() {\nSystem.out.println("Car");\n}\n}\nVehicle v = new Car();\nv.move();',
    options: ['Vehicle', 'Car', 'VehicleCar', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-01', difficulty: 'medium', category: 'DSA-Arrays',
    question: 'int a[] = {2, 5, 8, 11};\nfor(int i = 1; i < 4; i++) a[i] = a[i] - a[i-1];\nprintf("%d", a[3]);',
    options: ['6', '8', '9', '11'],
    correctIndex: 2 },
  { id: 'q-m-02', difficulty: 'medium', category: 'DSA-Arrays',
    question: 'int a[] = {4, 7, 2, 9, 5};\nint count = 0;\nfor(int i = 0; i < 5; i++) if(a[i] > a[0]) count++;\nprintf("%d", count);',
    options: ['2', '3', '4', '5'],
    correctIndex: 1 },
  { id: 'q-m-03', difficulty: 'medium', category: 'DSA-Arrays',
    question: 'int a[] = {3, 8, 6, 10, 4};\nint count = 0;\nfor(int i = 0; i < 4; i++) if(a[i] < a[i+1]) count++;\nprintf("%d", count);',
    options: ['1', '2', '3', '4'],
    correctIndex: 1 },
  { id: 'q-m-04', difficulty: 'medium', category: 'C-Basics',
    question: 'int a[] = {10, 20, 30, 40};\nint i = 1;\na[i] = a[i++] + 5;\nWhat is the safest conclusion about this statement in C?',
    options: ['a[1] becomes 25', 'a[2] becomes 25', 'The expression has undefined behavior', 'Compilation always fails'],
    correctIndex: 2 },
  { id: 'q-m-05', difficulty: 'medium', category: 'DSA-Arrays',
    question: 'For an array of n elements, which pair of positions should be swapped first when reversing the array in-place?',
    options: ['0 and n', '0 and n-1', '1 and n-1', '1 and n'],
    correctIndex: 1 },
  { id: 'q-m-06', difficulty: 'medium', category: 'DSA-Arrays',
    question: 'int a[] = {1, 2, 1, 3, 2};\nWhich value is encountered as a duplicate first when scanning left to right?',
    options: ['1', '2', '3', 'No duplicate'],
    correctIndex: 0 },
  { id: 'q-m-07', difficulty: 'medium', category: 'DSA-Stacks',
    question: 'Which pop sequence is possible for a stack if elements are pushed in the order 1, 2, 3?',
    options: ['2, 1, 3', '3, 1, 2', '1, 3, 2', '2, 3, 1'],
    correctIndex: 2 },
  { id: 'q-m-08', difficulty: 'medium', category: 'DSA-Stacks',
    question: 'Starting empty: push(4), push(7), pop(), push(9), push(2), pop()\nWhat is the complete stack from bottom to top?',
    options: ['4, 9', '4, 7, 9', '4, 9, 2', '7, 9'],
    correctIndex: 0 },
  { id: 'q-m-09', difficulty: 'medium', category: 'DSA-Stacks',
    question: 'An editor stores each character typed so that Undo removes the most recently typed character. Which principle is used?',
    options: ['FIFO', 'LIFO', 'Random access', 'Priority ordering'],
    correctIndex: 1 },
  { id: 'q-m-10', difficulty: 'medium', category: 'DSA-Stacks',
    question: 'A stack has capacity 3 and currently contains three elements. What happens when another element is pushed, assuming no resizing?',
    options: ['Underflow', 'Overflow', 'Bottom element is removed', 'Top is replaced'],
    correctIndex: 1 },
  { id: 'q-m-11', difficulty: 'medium', category: 'DSA-Queues',
    question: 'Starting empty: enqueue(5), enqueue(8), dequeue(), enqueue(12), enqueue(15)\nWhat is the queue from front to rear?',
    options: ['5, 12, 15', '8, 12, 15', '8, 15, 12', '12, 15'],
    correctIndex: 1 },
  { id: 'q-m-12', difficulty: 'medium', category: 'DSA-Queues',
    question: 'Why are separate front and rear positions commonly maintained in an efficient array queue?',
    options: ['To sort the queue', 'To know where deletion and insertion occur', 'To store two copies of each element', 'To make it LIFO'],
    correctIndex: 1 },
  { id: 'q-m-13', difficulty: 'medium', category: 'DSA-Queues',
    question: 'In a circular queue, rear reaches the last array position while unused positions exist at the beginning. What can a correct implementation do?',
    options: ['Always report overflow', 'Wrap rear to the beginning', 'Delete the front automatically', 'Reverse the queue'],
    correctIndex: 1 },
  { id: 'q-m-14', difficulty: 'medium', category: 'DSA-Queues',
    question: 'A queue receives A, B, C, D. Then two elements are removed and E is inserted. What is the new front?',
    options: ['A', 'B', 'C', 'E'],
    correctIndex: 2 },
  { id: 'q-m-15', difficulty: 'medium', category: 'DSA-Basics',
    question: 'You need to repeatedly process the item that arrived earliest. Which structure most directly matches?',
    options: ['Stack', 'Queue', 'Binary tree', 'Hash table'],
    correctIndex: 1 },
  { id: 'q-m-16', difficulty: 'medium', category: 'DSA-Recursion',
    question: 'int fun(int n) {\nif(n <= 1) return n;\nreturn fun(n-1) + 2;\n}\nWhat does fun(4) return?',
    options: ['4', '5', '6', '7'],
    correctIndex: 2 },
  { id: 'q-m-17', difficulty: 'medium', category: 'DSA-Recursion',
    question: 'void fun(int n) {\nif(n == 0) return;\nprintf("%d ", n);\nfun(n-1);\n}\nWhat is the last number printed by fun(5)?',
    options: ['5', '2', '1', '0'],
    correctIndex: 2 },
  { id: 'q-m-18', difficulty: 'medium', category: 'DSA-Recursion',
    question: 'int sum(int n) {\nif(n == 1) return 1;\nreturn n + sum(n-1);\n}\nWhat is sum(5)?',
    options: ['10', '15', '20', '25'],
    correctIndex: 1 },
  { id: 'q-m-19', difficulty: 'medium', category: 'DSA-Recursion',
    question: 'int fun(int n) {\nif(n <= 1) return 1;\nreturn fun(n-1) + fun(n-2);\n}\nHow many times is fun() called while evaluating fun(3), including the original call?',
    options: ['3', '4', '5', '6'],
    correctIndex: 2 },
  { id: 'q-m-20', difficulty: 'medium', category: 'DSA-Recursion',
    question: 'void fun(int n) {\nif(n == 0) return;\nfun(n-1);\nprintf("%d ", n);\nfun(n-1);\n}\nWhat is printed by fun(2)?',
    options: ['1 2 1', '2 1 1', '1 1 2', '2 1 2'],
    correctIndex: 0 },
  { id: 'q-m-21', difficulty: 'medium', category: 'C-Basics',
    question: 'void change(int a[]) { a[1] = 99; }\nint main() {\nint a[] = {10,20,30};\nchange(a);\nprintf("%d", a[1]);\n}',
    options: ['20', '30', '99', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-m-22', difficulty: 'medium', category: 'C-Basics',
    question: 'int x = 6, y = 4;\nprintf("%d", x & y);',
    options: ['0', '2', '4', '10'],
    correctIndex: 2 },
  { id: 'q-m-23', difficulty: 'medium', category: 'C-Basics',
    question: 'int x = 0;\nif(x != 0 && 10/x > 1) printf("A");\nelse printf("B");\nWhat is printed?',
    options: ['A', 'B', 'Division by zero', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-24', difficulty: 'medium', category: 'C-Basics',
    question: 'int x = 5;\nif(x == 5 || ++x > 5) printf("%d", x);',
    options: ['5', '6', '1', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-m-25', difficulty: 'medium', category: 'C-Pointers',
    question: 'int x = 7;\nint *p = &x;\nint **q = &p;\n**q = 12;\nprintf("%d", x);',
    options: ['7', '12', 'Address of p', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-26', difficulty: 'medium', category: 'C-Pointers',
    question: 'int a[] = {10,20,30,40};\nint *p = &a[0];\nint *q = &a[3];\nWhat does q - p represent?',
    options: ['3', '12 bytes always', '30', '4'],
    correctIndex: 0 },
  { id: 'q-m-27', difficulty: 'medium', category: 'C-Pointers',
    question: 'int a[] = {10,20,30};\nint *p = &a[0];\nprintf("%d ", *p);\np++;\nprintf("%d", *p);',
    options: ['10 10', '10 20', '20 30', '10 30'],
    correctIndex: 1 },
  { id: 'q-m-28', difficulty: 'medium', category: 'C-Pointers',
    question: 'int x = 10;\nint *p = &x;\nint *q = p;\n*q = 50;\nWhat is x?',
    options: ['10', '50', 'Address of p', 'Undefined'],
    correctIndex: 1 },
  { id: 'q-m-29', difficulty: 'medium', category: 'C-Pointers',
    question: 'int a[] = {10,20,30};\nint *p = a;\nprintf("%d", *p + *(p+1));',
    options: ['10', '20', '30', '40'],
    correctIndex: 2 },
  { id: 'q-m-30', difficulty: 'medium', category: 'C-Pointers',
    question: 'int x = 5;\nint *p = &x;\nprintf("%d", *p++);\nWhat value is printed?',
    options: ['5', '6', 'Address of x', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-m-31', difficulty: 'medium', category: 'C-Structures',
    question: 'struct Point { int x; int y; };\nstruct Point a = {2, 3};\nstruct Point b = a;\nb.x = 10;\nWhat is a.x?',
    options: ['2', '3', '10', 'Undefined'],
    correctIndex: 0 },
  { id: 'q-m-32', difficulty: 'medium', category: 'C-Structures',
    question: 'struct Student { int marks; };\nstruct Student s[3] = {{60}, {75}, {90}};\nfor(int i = 0; i < 3; i++)\nif(s[i].marks >= 75) printf("%d ", s[i].marks);',
    options: ['60 75 90', '75 90', '60 90', '90'],
    correctIndex: 1 },
  { id: 'q-m-33', difficulty: 'medium', category: 'C-Structures',
    question: 'struct Point { int x; };\nstruct Point p = {10};\nstruct Point *q = &p;\n(*q).x = 25;\nprintf("%d", p.x);',
    options: ['10', '25', 'Address', 'Error'],
    correctIndex: 1 },
  { id: 'q-m-34', difficulty: 'medium', category: 'C-Structures',
    question: 'struct Student { int marks; };\nstruct Student a = {80};\nstruct Student b = a;\nb.marks += 10;\nprintf("%d %d", a.marks, b.marks);',
    options: ['80 80', '90 90', '80 90', '90 80'],
    correctIndex: 2 },
  { id: 'q-m-35', difficulty: 'medium', category: 'C-Preprocessor',
    question: '#define DOUBLE(x) (2 * (x))\nprintf("%d", DOUBLE(3 + 2));',
    options: ['7', '10', '8', '12'],
    correctIndex: 1 },
  { id: 'q-m-36', difficulty: 'medium', category: 'C-Preprocessor',
    question: '#define SQUARE(x) ((x) * (x))\nint a = 3;\nprintf("%d", SQUARE(a + 1));',
    options: ['7', '12', '16', '10'],
    correctIndex: 2 },
  { id: 'q-m-37', difficulty: 'medium', category: 'C-Preprocessor',
    question: '#define MAX(a,b) ((a) > (b) ? (a) : (b))\nint x = 4, y = 7;\nprintf("%d", MAX(x++, y++));\nWhat is the main concern?',
    options: ['MAX is always a function', 'An argument can be evaluated more than once', 'x and y cannot be incremented', 'Macro cannot use ?:'],
    correctIndex: 1 },
  { id: 'q-m-38', difficulty: 'medium', category: 'Python-Lists',
    question: 'a = [1, 2, 3]\nb = a\nb[1] = 99\nprint(a[1])',
    options: ['2', '3', '99', 'Error'],
    correctIndex: 2 },
  { id: 'q-m-39', difficulty: 'medium', category: 'Python-Lists',
    question: 'a = [1, 2, 3]\nb = a[:]\nb[0] = 50\nprint(a[0])',
    options: ['1', '50', '0', 'Error'],
    correctIndex: 0 },
  { id: 'q-m-40', difficulty: 'medium', category: 'Python-Lists',
    question: 'x = [0,1,2,3,4,5]\nprint(x[1:5:2])',
    options: ['[1,2,3,4]', '[1,3]', '[0,2,4]', '[2,4]'],
    correctIndex: 1 },
  { id: 'q-m-41', difficulty: 'medium', category: 'Python-Lists',
    question: 'x = [1,2,3,4]\nprint(x[::-1])',
    options: ['[1,2,3,4]', '[4,3,2,1]', '[4,3,2]', 'Error'],
    correctIndex: 1 },
  { id: 'q-m-42', difficulty: 'medium', category: 'Python-Loops',
    question: 'for i in range(3):\nif i == 1:\nbreak\nelse:\nprint("Done")\nWhat is printed?',
    options: ['Done', '0', 'Nothing', '0 Done'],
    correctIndex: 2 },
  { id: 'q-m-43', difficulty: 'medium', category: 'Python-Lists',
    question: 'a = [[1,2], [3,4]]\nb = a.copy()\nb[0][0] = 99\nprint(a[0][0])',
    options: ['1', '2', '99', 'Error'],
    correctIndex: 2 },
  { id: 'q-m-44', difficulty: 'medium', category: 'Python-Functions',
    question: 'def fun(x):\nif x > 5:\nreturn x * 2\nreturn x + 2\nprint(fun(5))',
    options: ['5', '7', '10', '12'],
    correctIndex: 1 },
  { id: 'q-m-45', difficulty: 'medium', category: 'Python-Basics',
    question: 'x = {1, 2, 2, 3}\nprint(len(x))',
    options: ['2', '3', '4', 'Error'],
    correctIndex: 1 },
  { id: 'q-m-46', difficulty: 'medium', category: 'Python-Basics',
    question: 'x = [0]\nif x:\nprint("True")\nelse:\nprint("False")',
    options: ['True', 'False', '0', 'Error'],
    correctIndex: 0 },
  { id: 'q-m-47', difficulty: 'medium', category: 'Python-Dictionaries',
    question: 'd = {"a": 1, "b": 2}\nd["c"] = d["a"] + d["b"]\nprint(d["c"])',
    options: ['1', '2', '3', 'Error'],
    correctIndex: 2 },
  { id: 'q-m-48', difficulty: 'medium', category: 'Python-Loops',
    question: 'count = 0\nfor i in range(2):\nfor j in range(3):\ncount += 1\nprint(count)',
    options: ['3', '5', '6', '9'],
    correctIndex: 2 },
  { id: 'q-m-49', difficulty: 'medium', category: 'Java-Constructors',
    question: 'class A {\nint x;\nA() { x = 10; }\n}\nA obj = new A();\nSystem.out.println(obj.x);',
    options: ['0', '10', 'null', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-50', difficulty: 'medium', category: 'Java-Basics',
    question: 'class A {\nint x = 5;\nvoid set(int x) { this.x = x; }\n}\nA obj = new A();\nobj.set(20);\nWhat is obj.x?',
    options: ['5', '20', '25', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-51', difficulty: 'medium', category: 'Java-Polymorphism',
    question: 'class Test {\nvoid show(int x) { System.out.println("int"); }\nvoid show(double x) { System.out.println("double"); }\n}\nTest t = new Test();\nt.show(5);',
    options: ['int', 'double', 'int double', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-m-52', difficulty: 'medium', category: 'Java-Inheritance',
    question: 'class A { int x = 10; }\nclass B extends A { int y = 20; }\nB obj = new B();\nWhat can obj directly access?',
    options: ['Only y', 'Only x', 'x and y', 'Neither'],
    correctIndex: 2 },
  { id: 'q-m-53', difficulty: 'medium', category: 'Java-Polymorphism',
    question: 'class A { void show() { System.out.println("A"); } }\nclass B extends A { void show() { System.out.println("B"); } }\nA obj = new B();\nobj.show();',
    options: ['A', 'B', 'A B', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-54', difficulty: 'medium', category: 'Java-Static',
    question: 'class Test { static int x = 5; }\nTest a = new Test();\nTest b = new Test();\na.x = 20;\nSystem.out.println(b.x);',
    options: ['5', '20', '0', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-55', difficulty: 'medium', category: 'Java-Encapsulation',
    question: 'class Student {\nprivate int marks = 80;\npublic int getMarks() { return marks; }\n}\nStudent s = new Student();\nSystem.out.println(s.getMarks());',
    options: ['0', '80', 'private', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-56', difficulty: 'medium', category: 'Java-Inheritance',
    question: 'class A { int x = 10; }\nclass B extends A {\nint x = 20;\nvoid show() { System.out.println(super.x); }\n}\nnew B().show();',
    options: ['10', '20', '30', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-m-57', difficulty: 'medium', category: 'Java-Polymorphism',
    question: 'class Animal { void sound() { System.out.println("Animal"); } }\nclass Dog extends Animal { void sound() { System.out.println("Dog"); } }\nAnimal a = new Dog();\na.sound();\nWhich determines the overridden method that runs?',
    options: ['Only declared type', 'Actual object type at runtime', 'Class name of Animal', 'Constructor return type'],
    correctIndex: 1 },
  { id: 'q-m-58', difficulty: 'medium', category: 'Java-Constructors',
    question: 'class Box {\nBox() { System.out.println("A"); }\nBox(int x) { System.out.println("B"); }\n}\nnew Box(5);',
    options: ['A', 'B', 'A B', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-m-59', difficulty: 'medium', category: 'Java-Static',
    question: 'class Test {\nstatic int count = 0;\nTest() { count++; }\n}\nTest a = new Test();\nTest b = new Test();\nSystem.out.println(a.count);',
    options: ['0', '1', '2', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-m-60', difficulty: 'medium', category: 'Java-Inheritance',
    question: 'class A { void show() { System.out.print("A"); } }\nclass B extends A {\nvoid show() {\nsuper.show();\nSystem.out.print("B");\n}\n}\nnew B().show();',
    options: ['A', 'B', 'AB', 'BA'],
    correctIndex: 2 },
  { id: 'q-mh-01', difficulty: 'medium_hard', category: 'DSA-Arrays',
    question: 'int a[] = {2, 4, 6, 8};\nfor(int i = 1; i < 4; i++)\na[i] += a[i-1];\nprintf("%d %d", a[2], a[3]);',
    options: ['6 8', '12 20', '12 26', '10 18'],
    correctIndex: 2 },
  { id: 'q-mh-02', difficulty: 'medium_hard', category: 'DSA-Arrays',
    question: 'int a[] = {1,2,3,4,5};\nint temp = a[0];\nfor(int i = 0; i < 4; i++)\na[i] = a[i+1];\na[4] = temp;\nWhat is the resulting array?',
    options: ['2 3 4 5 1', '5 1 2 3 4', '1 3 4 5 2', '2 1 3 4 5'],
    correctIndex: 0 },
  { id: 'q-mh-03', difficulty: 'medium_hard', category: 'DSA-Arrays',
    question: 'int a[] = {1, 3, 4, 6, 8};\nint i = 0, j = 4, count = 0;\nwhile(i < j) {\nif(a[i] + a[j] > 9)\nj--;\nelse {\ncount++;\ni++;\n}\n}\nWhat is count?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2 },
  { id: 'q-mh-04', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'int a[4] = {10,20,30,40};\nfor(int i = 0; i <= 4; i++)\nprintf("%d ", a[i]);\nWhich statement is correct?',
    options: ['It prints all four values safely', 'It prints five values, with the fifth being 0', 'Accessing a[4] is outside the array and causes undefined behavior', 'Compilation always fails'],
    correctIndex: 2 },
  { id: 'q-mh-05', difficulty: 'medium_hard', category: 'DSA-Arrays',
    question: 'int a[] = {2,3,2,4,3,2};\nint count = 0;\nfor(int i = 0; i < 6; i++)\nif(a[i] == 2) count++;\nWhat is count?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1 },
  { id: 'q-mh-06', difficulty: 'medium_hard', category: 'DSA-Arrays',
    question: 'int a[] = {5,2,8,1,4};\nAfter the first complete pass of selection sort in ascending order, what is the array?',
    options: ['1 2 8 5 4', '1 2 5 8 4', '2 5 8 1 4', '1 4 8 5 2'],
    correctIndex: 0 },
  { id: 'q-mh-07', difficulty: 'medium_hard', category: 'DSA-Stacks',
    question: 'Push: 10, 20, 30\nPop\nPush: 40\nPop\nPop\nWhich value remains on top?',
    options: ['10', '20', '30', '40'],
    correctIndex: 1 },
  { id: 'q-mh-08', difficulty: 'medium_hard', category: 'DSA-Stacks',
    question: 'Elements 1, 2, 3, 4 are pushed in that order. Which output sequence is NOT possible from a stack?',
    options: ['4 3 2 1', '2 1 4 3', '3 2 4 1', '3 1 4 2'],
    correctIndex: 3 },
  { id: 'q-mh-09', difficulty: 'medium_hard', category: 'DSA-Stacks',
    question: 'A stack uses top = -1 initially. After three pushes and one pop, what is top?',
    options: ['0', '1', '2', '3'],
    correctIndex: 1 },
  { id: 'q-mh-10', difficulty: 'medium_hard', category: 'DSA-Stacks',
    question: 'A stack is used to check balanced parentheses. When a closing \')\' is encountered, what should normally happen?',
    options: ['Push it', 'Pop and compare with the matching opening symbol', 'Clear the stack', 'Ignore it'],
    correctIndex: 1 },
  { id: 'q-mh-11', difficulty: 'medium_hard', category: 'DSA-Queues',
    question: 'Queue: front -> 11, 22, 33, 44\ndequeue()\ndequeue()\nenqueue(55)\nenqueue(66)\nWhat is the front-to-rear order?',
    options: ['33 44 55 66', '11 22 55 66', '44 33 55 66', '33 44 66 55'],
    correctIndex: 0 },
  { id: 'q-mh-12', difficulty: 'medium_hard', category: 'DSA-Queues',
    question: 'A circular queue has size 5 and rear is at index 4. One more enqueue is possible because index 0 is free. Where should rear move?',
    options: ['4', '5', '0', '-1'],
    correctIndex: 2 },
  { id: 'q-mh-13', difficulty: 'medium_hard', category: 'DSA-Queues',
    question: 'A queue is empty. Which operation is invalid if there is no special error handling?',
    options: ['Enqueue', 'Dequeue', 'Peek after enqueue', 'Enqueue twice'],
    correctIndex: 1 },
  { id: 'q-mh-14', difficulty: 'medium_hard', category: 'DSA-Queues',
    question: 'In a simple array implementation where dequeue shifts every remaining element one position toward the front, what is the worst-case time complexity of dequeue?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctIndex: 2 },
  { id: 'q-mh-15', difficulty: 'medium_hard', category: 'DSA-Queues',
    question: 'A circular queue has size 4. If front = 2 and rear = 1, which interpretation can be correct?',
    options: ['It must be empty', 'It can represent a full queue', 'It must contain exactly one element', 'It is always invalid'],
    correctIndex: 1 },
  { id: 'q-mh-16', difficulty: 'medium_hard', category: 'DSA-Recursion',
    question: 'int f(int n) {\nif(n <= 0) return 0;\nreturn n + f(n-2);\n}\nWhat is f(6)?',
    options: ['6', '9', '12', '21'],
    correctIndex: 1 },
  { id: 'q-mh-17', difficulty: 'medium_hard', category: 'DSA-Recursion',
    question: 'void f(int n) {\nif(n == 0) return;\nf(n-1);\nprintf("%d ", n);\n}\nWhat is printed by f(3)?',
    options: ['3 2 1', '1 2 3', '0 1 2', '3 1 2'],
    correctIndex: 1 },
  { id: 'q-mh-18', difficulty: 'medium_hard', category: 'DSA-Recursion',
    question: 'int digits(int n) {\nif(n < 10) return 1;\nreturn 1 + digits(n/10);\n}\nWhat does digits(5082) return?',
    options: ['3', '4', '5', '508'],
    correctIndex: 1 },
  { id: 'q-mh-19', difficulty: 'medium_hard', category: 'DSA-Recursion',
    question: 'int f(int n) {\nif(n == 0) return 1;\nreturn n * f(n-1);\n}\nWhat is f(4)?',
    options: ['10', '16', '24', '25'],
    correctIndex: 2 },
  { id: 'q-mh-20', difficulty: 'medium_hard', category: 'DSA-Recursion',
    question: 'int f(int n) {\nif(n <= 1) return n;\nreturn f(n-1) + f(n-2);\n}\nWhat is f(5)?',
    options: ['3', '5', '8', '13'],
    correctIndex: 2 },
  { id: 'q-mh-21', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'int x = 3;\nprintf("%d %d", x++, ++x);\nWhich statement is correct in C?',
    options: ['Always prints 3 5', 'Always prints 4 4', 'The expression has undefined behavior', 'It cannot compile'],
    correctIndex: 2 },
  { id: 'q-mh-22', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'int x = 2;\nswitch(x) {\ncase 1: printf("A");\ncase 2: printf("B");\ncase 3: printf("C");\n}\nWhat is printed?',
    options: ['B', 'BC', 'ABC', 'C'],
    correctIndex: 1 },
  { id: 'q-mh-23', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'void f() {\nstatic int x = 0;\nx++;\nprintf("%d ", x);\n}\nf();\nf();\nf();\nWhat is printed?',
    options: ['1 1 1', '0 1 2', '1 2 3', '1 2 2'],
    correctIndex: 2 },
  { id: 'q-mh-24', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'int a[5];\nprintf("%zu", sizeof(a) / sizeof(a[0]));\nWhat does the expression represent?',
    options: ['Number of bytes in a', 'Number of elements in a', 'Size of one pointer', 'Always 5 bytes'],
    correctIndex: 1 },
  { id: 'q-mh-25', difficulty: 'medium_hard', category: 'C-Basics',
    question: 'int x = 8, y = 3;\nint z = x > y ? x - y : y - x;\nprintf("%d", z);',
    options: ['3', '5', '8', '11'],
    correctIndex: 1 },
  { id: 'q-mh-26', difficulty: 'medium_hard', category: 'C-Pointers',
    question: 'int a[] = {5,10,15};\nint *p = a + 1;\n*p = *p + *(p-1);\nWhat is a[1]?',
    options: ['5', '10', '15', '20'],
    correctIndex: 2 },
  { id: 'q-mh-27', difficulty: 'medium_hard', category: 'C-Pointers',
    question: 'int a[] = {4,7,9,12};\nint *p = a;\nprintf("%d ", *(p+2));\np += 1;\nprintf("%d", *p);',
    options: ['4 7', '9 7', '9 9', '7 9'],
    correctIndex: 1 },
  { id: 'q-mh-28', difficulty: 'medium_hard', category: 'C-Pointers',
    question: 'void swap(int *a, int *b) {\nint t = *a;\n*a = *b;\n*b = t;\n}\nint x=4, y=9;\nswap(&x,&y);\nWhat are x and y?',
    options: ['4 9', '9 4', '13 13', 'Addresses'],
    correctIndex: 1 },
  { id: 'q-mh-29', difficulty: 'medium_hard', category: 'C-Pointers',
    question: 'int a[] = {10,20,30,40};\nint *p = &a[1];\nint *q = &a[3];\nHow many array elements apart are p and q?',
    options: ['1', '2', '3', '8'],
    correctIndex: 1 },
  { id: 'q-mh-30', difficulty: 'medium_hard', category: 'C-Pointers',
    question: 'int a[] = {10,20,30};\nint *p = a;\nprintf("%d ", *p++);\nprintf("%d", *p);',
    options: ['10 10', '10 20', '20 30', '11 20'],
    correctIndex: 1 },
  { id: 'q-mh-31', difficulty: 'medium_hard', category: 'C-Structures',
    question: 'struct Student {\nint marks;\n};\nstruct Student s = {70};\nstruct Student *p = &s;\np->marks += 15;\nWhat is s.marks?',
    options: ['70', '75', '85', '105'],
    correctIndex: 2 },
  { id: 'q-mh-32', difficulty: 'medium_hard', category: 'C-Structures',
    question: 'struct Item {\nint price;\n};\nstruct Item a[3] = {{20}, {50}, {30}};\nint max = a[0].price;\nfor(int i=1;i<3;i++)\nif(a[i].price > max) max = a[i].price;\nWhat is max?',
    options: ['20', '30', '50', '100'],
    correctIndex: 2 },
  { id: 'q-mh-33', difficulty: 'medium_hard', category: 'C-Structures',
    question: 'struct Date { int day; int month; };\nstruct Student { struct Date dob; };\nstruct Student s = {{12, 8}};\nprintf("%d", s.dob.month);',
    options: ['8', '12', '20', 'Error'],
    correctIndex: 0 },
  { id: 'q-mh-34', difficulty: 'medium_hard', category: 'C-Structures',
    question: 'struct Point { int x; int y; };\nstruct Point p = {3,4};\nstruct Point *q = &p;\nWhich expression correctly accesses y through q?',
    options: ['q.y', '*q.y', 'q->y', '&q.y'],
    correctIndex: 2 },
  { id: 'q-mh-35', difficulty: 'medium_hard', category: 'C-Structures',
    question: 'struct S { int x; };\nstruct S a[2] = {{5},{10}};\nstruct S *p = a;\n(p+1)->x += 5;\nprintf("%d", a[1].x);',
    options: ['5', '10', '15', '20'],
    correctIndex: 2 },
  { id: 'q-mh-36', difficulty: 'medium_hard', category: 'C-Preprocessor',
    question: '#define SQUARE(x) x*x\nint a = 2 + 3;\nprintf("%d", SQUARE(a));',
    options: ['25', '10', '7', '11'],
    correctIndex: 1 },
  { id: 'q-mh-37', difficulty: 'medium_hard', category: 'C-Preprocessor',
    question: '#define ADD(a,b) a+b\nprintf("%d", 2 * ADD(3,4));',
    options: ['14', '10', '9', '24'],
    correctIndex: 0 },
  { id: 'q-mh-38', difficulty: 'medium_hard', category: 'C-Preprocessor',
    question: '#define DEBUG\n#ifdef DEBUG\nprintf("D");\n#else\nprintf("N");\n#endif\nWhat is printed?',
    options: ['D', 'N', 'DEBUG', 'Nothing'],
    correctIndex: 0 },
  { id: 'q-mh-39', difficulty: 'medium_hard', category: 'C-Preprocessor',
    question: '#define INC(x) ((x)+1)\nint a = 5;\nint b = INC(a * 2);\nWhat is b?',
    options: ['10', '11', '12', '6'],
    correctIndex: 1 },
  { id: 'q-mh-40', difficulty: 'medium_hard', category: 'C-Preprocessor',
    question: '#define CUBE(x) ((x)*(x)*(x))\nint x = 2;\nprintf("%d", CUBE(x++));\nWhich is the best answer?',
    options: ['8', '9', 'The expression has undefined behavior', 'Compilation always fails'],
    correctIndex: 2 },
  { id: 'q-mh-41', difficulty: 'medium_hard', category: 'Python-Functions',
    question: 'def add(x, a=[]):\na.append(x)\nreturn a\nprint(add(1))\nprint(add(2))\nWhat is printed?',
    options: ['[1] then [2]', '[1] then [1, 2]', '[1, 2] then [1, 2]', 'Error'],
    correctIndex: 1 },
  { id: 'q-mh-42', difficulty: 'medium_hard', category: 'Python-Lists',
    question: 'x = [1,2,3,4,5]\ny = [n*n for n in x if n % 2 == 0]\nWhat is y?',
    options: ['[1,4,9,16,25]', '[2,4]', '[4,16]', '[1,9,25]'],
    correctIndex: 2 },
  { id: 'q-mh-43', difficulty: 'medium_hard', category: 'Python-Dictionaries',
    question: 'd = {"a": 10, "b": 20}\nd["a"] += 5\nd["c"] = d["a"] + d["b"]\nprint(d["c"])',
    options: ['30', '35', '40', '45'],
    correctIndex: 2 },
  { id: 'q-mh-44', difficulty: 'medium_hard', category: 'Python-Loops',
    question: 'x = 0\nfor i in range(1,5):\nif i == 3:\ncontinue\nx += i\nprint(x)',
    options: ['7', '8', '9', '10'],
    correctIndex: 1 },
  { id: 'q-mh-45', difficulty: 'medium_hard', category: 'Python-Lists',
    question: 'a = [1,2,3,4]\na[1:3] = [8,9,10]\nprint(a)',
    options: ['[1,8,9,4]', '[1,8,9,10,4]', '[8,9,10,4]', 'Error'],
    correctIndex: 1 },
  { id: 'q-mh-46', difficulty: 'medium_hard', category: 'Python-Basics',
    question: 'a = [1,2]\nb = [1,2]\nWhich statement is true?',
    options: ['a is b and a == b', 'a is not b but a == b', 'a is b but a != b', 'Both are false'],
    correctIndex: 1 },
  { id: 'q-mh-47', difficulty: 'medium_hard', category: 'Python-Basics',
    question: 's = "cat"\ns[0] = "b"\nWhat happens?',
    options: ['s becomes "bat"', 's becomes "cbt"', 'A TypeError occurs', 'Nothing happens'],
    correctIndex: 2 },
  { id: 'q-mh-48', difficulty: 'medium_hard', category: 'Python-Lists',
    question: 'a = [[1], [2]]\nb = a[:]\nb.append([3])\nb[0].append(9)\nWhat is a?',
    options: ['[[1], [2]]', '[[1,9], [2]]', '[[1], [2], [3]]', '[[1,9], [2], [3]]'],
    correctIndex: 1 },
  { id: 'q-mh-49', difficulty: 'medium_hard', category: 'Java-Inheritance',
    question: 'class A {\nA() { System.out.print("A"); }\n}\nclass B extends A {\nB() { System.out.print("B"); }\n}\nnew B();\nWhat is printed?',
    options: ['A', 'B', 'AB', 'BA'],
    correctIndex: 2 },
  { id: 'q-mh-50', difficulty: 'medium_hard', category: 'Java-Polymorphism',
    question: 'class Test {\nvoid show(int x) { System.out.print("I"); }\nvoid show(double x) { System.out.print("D"); }\n}\nnew Test().show(3.0);',
    options: ['I', 'D', 'ID', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-mh-51', difficulty: 'medium_hard', category: 'Java-Inheritance',
    question: 'class A { int x = 10; }\nclass B extends A { int x = 20; }\nA obj = new B();\nSystem.out.println(obj.x);',
    options: ['10', '20', '30', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-mh-52', difficulty: 'medium_hard', category: 'Java-Polymorphism',
    question: 'class A { void show() { System.out.print("A"); } }\nclass B extends A { void show() { System.out.print("B"); } }\nB b = new B();\nA a = b;\na.show();',
    options: ['A', 'B', 'AB', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-mh-53', difficulty: 'medium_hard', category: 'Java-Basics',
    question: 'final int x = 10;\nx = 20;\nWhat happens?',
    options: ['x becomes 20', 'x becomes 30', 'Compilation error', 'Runtime error only'],
    correctIndex: 2 },
  { id: 'q-mh-54', difficulty: 'medium_hard', category: 'Java-Encapsulation',
    question: 'class A {\nprivate int x = 10;\n}\nclass B extends A {\nvoid show() {\n// direct access to x here\n}\n}\nCan B directly access A\'s private x?',
    options: ['Yes', 'No', 'Only with super.x', 'Only if x is static'],
    correctIndex: 1 },
  { id: 'q-mh-55', difficulty: 'medium_hard', category: 'Java-Static',
    question: 'class Test {\nstatic int x = 10;\nstatic void change() { x += 5; }\n}\nTest.change();\nSystem.out.println(Test.x);',
    options: ['10', '15', '20', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-mh-56', difficulty: 'medium_hard', category: 'Java-Inheritance',
    question: 'class A {}\nclass B extends A {}\nA obj = new B();\nB ref = (B)obj;\nWhich statement is correct?',
    options: ['The cast is valid', 'The cast always creates a new B object', 'The cast changes obj\'s actual object', 'Casting is forbidden'],
    correctIndex: 0 },
  { id: 'q-mh-57', difficulty: 'medium_hard', category: 'Java-Constructors',
    question: 'class Test {\nint x;\nTest(int n) {\nx = n;\n}\n}\nTest t = new Test();\nWhat happens?',
    options: ['x becomes 0', 'x becomes null', 'Compilation error because no no-argument constructor exists', 'Runtime error'],
    correctIndex: 2 },
  { id: 'q-mh-58', difficulty: 'medium_hard', category: 'Java-Inheritance',
    question: 'class A {\nvoid show() { System.out.print("A"); }\n}\nclass B extends A {\n// no show() method\n}\nnew B().show();\nWhat is printed?',
    options: ['A', 'B', 'Nothing', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-mh-59', difficulty: 'medium_hard', category: 'Java-Static',
    question: 'class Counter {\nstatic int c = 0;\nCounter() { c++; }\n}\nCounter a = new Counter();\nCounter b = new Counter();\nCounter c = new Counter();\nSystem.out.println(Counter.c);',
    options: ['0', '1', '2', '3'],
    correctIndex: 3 },
  { id: 'q-mh-60', difficulty: 'medium_hard', category: 'Java-Polymorphism',
    question: 'class A {\nvoid show() { System.out.print("A"); }\n}\nclass B extends A {\nvoid show() {\nSystem.out.print("B");\n}\n}\nclass C extends B {\nvoid show() {\nsuper.show();\nSystem.out.print("C");\n}\n}\nA obj = new C();\nobj.show();',
    options: ['A', 'B', 'BC', 'ABC'],
    correctIndex: 2 },
  { id: 'q-h-01', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'int a[] = {5, 2, 7, 4, 9, 6};\nint b[6], k = 0;\nfor(int i=0;i<6;i++)\nif(a[i] % 2 == 0) b[k++] = a[i];\nfor(int i=0;i<6;i++)\nif(a[i] % 2 != 0) b[k++] = a[i];\nWhich is b?',
    options: ['2 4 6 5 7 9', '6 4 2 9 7 5', '2 4 6 7 5 9', '5 7 9 2 4 6'],
    correctIndex: 0 },
  { id: 'q-h-02', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'For the array:\n{-2, 3, -1, 5, -6, 4}\nWhat is the maximum possible sum of a contiguous subarray?',
    options: ['6', '7', '8', '9'],
    correctIndex: 1 },
  { id: 'q-h-03', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'An integer array contains n elements, each in the range 1 to n-1, and exactly one value occurs at least twice.\nWhich approach can detect a duplicate without sorting the array and without using extra O(n) storage?',
    options: ['Nested loops only', 'Use Floyd\'s cycle-detection idea on the value-to-index mapping', 'Binary search directly on the unsorted array', 'Merge sort'],
    correctIndex: 1 },
  { id: 'q-h-04', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'An array [1,2,3,4,5,6,7] is rotated right by 3 positions using the standard three-reversal method.\nWhat is the final array?',
    options: ['4 5 6 7 1 2 3', '5 6 7 1 2 3 4', '7 6 5 4 3 2 1', '3 2 1 7 6 5 4'],
    correctIndex: 0 },
  { id: 'q-h-05', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'For [3, 1, 2], how many inversions are present (Two array elements arr[i] and arr[j] form an inversion if arr[i] > arr[j] and i < j.)?',
    options: ['1', '2', '3', '0'],
    correctIndex: 1 },
  { id: 'q-h-06', difficulty: 'hard', category: 'DSA-Arrays',
    question: 'A sorted array is [2,4,6,8,10,12]. A binary search is used to find 10.\nIf the search first checks the middle element at index 2, which index is checked next?',
    options: ['0', '1', '4', '5'],
    correctIndex: 2 },
  { id: 'q-h-07', difficulty: 'hard', category: 'DSA-Stacks',
    question: 'A queue can be implemented using two stacks. To make dequeue behave like a normal queue, when the output stack is empty, what should be done?',
    options: ['Push the newest item directly into output', 'Move all items from input stack to output stack', 'Pop both stacks simultaneously', 'Reverse only the first element'],
    correctIndex: 1 },
  { id: 'q-h-08', difficulty: 'hard', category: 'DSA-Stacks',
    question: 'A stack-based algorithm scans stock prices and wants, for each day, the next greater price to its right.\nWhich stack property is most useful?',
    options: ['Keep indices whose corresponding values are waiting for a greater value', 'Keep only the smallest value', 'Sort all prices first', 'Store values permanently after they are popped'],
    correctIndex: 0 },
  { id: 'q-h-09', difficulty: 'hard', category: 'DSA-Stacks',
    question: 'A fixed-size stack has capacity 5 and currently contains 5 elements.\nWhich operation is invalid unless an element is removed first?',
    options: ['peek', 'pop', 'push', 'checking empty'],
    correctIndex: 2 },
  { id: 'q-h-10', difficulty: 'hard', category: 'DSA-Stacks',
    question: 'A stack contains, from bottom to top:\n4, 7, 4, 9\nAfter two pop operations, what is the top?',
    options: ['4', '7', '9', 'Empty'],
    correctIndex: 1 },
  { id: 'q-h-11', difficulty: 'hard', category: 'DSA-Queues',
    question: 'A linear queue uses front and rear indices and never shifts elements. After several dequeues, front has moved forward while rear reaches the final array index.\nEven if there are empty cells at the beginning, what problem occurs?',
    options: ['Stack overflow', 'False overflow / inability to enqueue at the rear', 'Recursion overflow', 'Underflow on every enqueue'],
    correctIndex: 1 },
  { id: 'q-h-12', difficulty: 'hard', category: 'DSA-Queues',
    question: 'In a circular queue implementation that reserves one slot to distinguish full from empty, which condition commonly indicates full?',
    options: ['(rear + 1) % size == front', 'rear == size', 'front == -1 only', 'rear == front always'],
    correctIndex: 0 },
  { id: 'q-h-13', difficulty: 'hard', category: 'DSA-Queues',
    question: 'Which statement best describes a deque?',
    options: ['Insertion only at rear and deletion only at front', 'Insertion and deletion can occur at both ends', 'Only deletion at both ends', 'It is always implemented with two stacks'],
    correctIndex: 1 },
  { id: 'q-h-14', difficulty: 'hard', category: 'DSA-Queues',
    question: 'Processes enter a queue in this order:\nP1, P2, P3\nP1 completes after one time slice and is reinserted at the rear before P2 gets its slice.\nWhat is the queue order immediately after P1 is reinserted?',
    options: ['P1 P2 P3', 'P2 P3 P1', 'P3 P2 P1', 'P2 P1 P3'],
    correctIndex: 1 },
  { id: 'q-h-15', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'int f(int n) {\nif(n <= 0) return 0;\nif(n % 2 == 0) return n + f(n-2);\nreturn n + f(n-1);\n}\nWhat is f(7)?',
    options: ['12', '16', '18', '28'],
    correctIndex: 2 },
  { id: 'q-h-16', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'int max(int a[], int n) {\nif(n == 1) return a[0];\nint m = max(a, n-1);\nreturn a[n-1] > m ? a[n-1] : m;\n}\nFor {4, 9, 2, 11, 7}, what is returned?',
    options: ['7', '9', '11', '33'],
    correctIndex: 2 },
  { id: 'q-h-17', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'int power(int x, int n) {\nif(n == 0) return 1;\nreturn x * power(x, n-1);\n}\nWhat is power(2,5)?',
    options: ['10', '16', '25', '32'],
    correctIndex: 3 },
  { id: 'q-h-18', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'int gcd(int a, int b) {\nif(b == 0) return a;\nreturn gcd(b, a % b);\n}\nWhat does gcd(84, 30) return?',
    options: ['2', '6', '12', '14'],
    correctIndex: 1 },
  { id: 'q-h-19', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'void f(int n) {\nif(n == 0) return;\nf(n);\n}\nWhat happens when f(3) is called?',
    options: ['It prints 3', 'It returns normally', 'It eventually causes stack overflow', 'It automatically treats n as n-1'],
    correctIndex: 2 },
  { id: 'q-h-20', difficulty: 'hard', category: 'DSA-Recursion',
    question: 'A recursive binary search checks the middle element. If the target is smaller than the middle element, which subproblem is correct?',
    options: ['Search the entire array again', 'Search only the left half', 'Search only the right half', 'Search the middle element repeatedly'],
    correctIndex: 1 },
  { id: 'q-h-21', difficulty: 'hard', category: 'C-Basics',
    question: 'int a = 5;\ndouble b = 2;\nprintf("%.1f", a / b);\nWhat is printed?',
    options: ['2.0', '2.5', '2', '3.0'],
    correctIndex: 1 },
  { id: 'q-h-22', difficulty: 'hard', category: 'C-Basics',
    question: 'int x = 0;\nif(x && ++x)\nprintf("A");\nWhat is x after the condition?',
    options: ['0', '1', 'Undefined', 'It depends on compiler'],
    correctIndex: 0 },
  { id: 'q-h-23', difficulty: 'hard', category: 'C-Basics',
    question: 'int x = 5;\nif(x || ++x)\nprintf("%d", x);\nWhat is printed?',
    options: ['5', '6', '1', 'Undefined'],
    correctIndex: 0 },
  { id: 'q-h-24', difficulty: 'hard', category: 'C-Basics',
    question: 'int x = 2, y = 3, z = 4;\nint r = x + y * z > 10;\nWhat is r?',
    options: ['0', '1', '14', '20'],
    correctIndex: 1 },
  { id: 'q-h-25', difficulty: 'hard', category: 'C-Pointers',
    question: 'int a[] = {11,22,33,44,55};\nint *p = &a[4];\np -= 3;\nprintf("%d", *p);',
    options: ['11', '22', '33', '44'],
    correctIndex: 1 },
  { id: 'q-h-26', difficulty: 'hard', category: 'C-Pointers',
    question: 'int x = 10, y = 20;\nint *p = &x;\nint **q = &p;\np = &y;\n**q += 5;\nWhat is y?',
    options: ['20', '25', '30', '15'],
    correctIndex: 1 },
  { id: 'q-h-27', difficulty: 'hard', category: 'C-Pointers',
    question: 'int x = 7;\nint *p = &x;\nint **q = &p;\nWhich expression gives the value 7?',
    options: ['q', '*q', '**q', '&q'],
    correctIndex: 2 },
  { id: 'q-h-28', difficulty: 'hard', category: 'C-Pointers',
    question: 'void f(int a[]) {\nprintf("%zu", sizeof(a));\n}\nint x[10];\nf(x);\nInside f, what does sizeof(a) measure?',
    options: ['Size of the original 10-element array', 'Size of a pointer', 'Always 10 bytes', 'Size of one int'],
    correctIndex: 1 },
  { id: 'q-h-29', difficulty: 'hard', category: 'C-Pointers',
    question: 'int x = 4, y = 9;\nint *const p = &x;\nWhich statement is valid?',
    options: ['p = &y;', '*p = 10;', 'p cannot be dereferenced', 'Both A and B'],
    correctIndex: 1 },
  { id: 'q-h-30', difficulty: 'hard', category: 'C-Pointers',
    question: 'int x = 4, y = 9;\nconst int *p = &x;\nWhich is valid?',
    options: ['*p = 7;', 'p = &y;', 'p = NULL is forbidden', 'Both A and B'],
    correctIndex: 1 },
  { id: 'q-h-31', difficulty: 'hard', category: 'C-Structures',
    question: 'struct A {\nchar c;\nint x;\n};\nWhy can sizeof(struct A) be greater than sizeof(char) + sizeof(int)?',
    options: ['Structures always duplicate every field', 'Padding may be inserted for alignment', 'int is stored twice', 'char is converted to double'],
    correctIndex: 1 },
  { id: 'q-h-32', difficulty: 'hard', category: 'C-Structures',
    question: 'struct S { int x; int y; };\nstruct S a[2] = {{1,2},{3,4}};\nstruct S *p = a;\nprintf("%d", (p+1)->y);',
    options: ['1', '2', '3', '4'],
    correctIndex: 3 },
  { id: 'q-h-33', difficulty: 'hard', category: 'C-Structures',
    question: 'struct S { int x; };\nstruct S a = {5};\nstruct S b = a;\nb.x = 9;\nWhat is a.x?',
    options: ['5', '9', '14', 'Undefined'],
    correctIndex: 0 },
  { id: 'q-h-34', difficulty: 'hard', category: 'C-Structures',
    question: 'struct Student {\nint marks;\n};\nstruct Student s[4] = {{72},{91},{68},{85}};\nint idx = 0;\nfor(int i=1;i<4;i++)\nif(s[i].marks > s[idx].marks)\nidx = i;\nWhat is idx?',
    options: ['0', '1', '2', '3'],
    correctIndex: 1 },
  { id: 'q-h-35', difficulty: 'hard', category: 'C-Structures',
    question: 'struct P { int x; };\nstruct P make() {\nstruct P p = {12};\nreturn p;\n}\nstruct P q = make();\nWhat is q.x?',
    options: ['0', '1', '12', 'Undefined'],
    correctIndex: 2 },
  { id: 'q-h-36', difficulty: 'hard', category: 'C-Preprocessor',
    question: '#define STR(x) #x\nprintf("%s", STR(hello));\nWhat is printed?',
    options: ['hello', '"hello"', 'x', 'STR'],
    correctIndex: 0 },
  { id: 'q-h-37', difficulty: 'hard', category: 'C-Preprocessor',
    question: '#define JOIN(a,b) a##b\nint xy = 25;\nprintf("%d", JOIN(x,y));\nWhat is printed?',
    options: ['25', 'xy', 'x y', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-h-38', difficulty: 'hard', category: 'C-Preprocessor',
    question: '#ifndef MY_H\n#define MY_H\n/* declarations */\n#endif\nWhat is the main purpose of this pattern?',
    options: ['Speed up loops', 'Prevent repeated inclusion of the same header contents', 'Allocate heap memory', 'Define a recursive function'],
    correctIndex: 1 },
  { id: 'q-h-39', difficulty: 'hard', category: 'C-Preprocessor',
    question: '#define FLAG 0\n#if FLAG\nint x = 1;\n#else\nint x = 2;\n#endif\nWhat is x?',
    options: ['0', '1', '2', 'Compilation error'],
    correctIndex: 2 },
  { id: 'q-h-40', difficulty: 'hard', category: 'C-Preprocessor',
    question: '#define NEG(x) -(x)\nint x = 3;\nint y = 2 * NEG(x);\nWhat is y?',
    options: ['-6', '-3', '6', '0'],
    correctIndex: 0 },
  { id: 'q-h-41', difficulty: 'hard', category: 'Python-Lists',
    question: 'a = [[0], [1]]\nb = a.copy()\nb[0] += [2]\nprint(a)',
    options: ['[[0],[1]]', '[[0,2],[1]]', '[[2],[1]]', 'Error'],
    correctIndex: 1 },
  { id: 'q-h-42', difficulty: 'hard', category: 'Python-Lists',
    question: 'a = [1,2,3]\nb = a\nb = b + [4]\nprint(a)',
    options: ['[1,2,3]', '[1,2,3,4]', '[4]', 'Error'],
    correctIndex: 0 },
  { id: 'q-h-43', difficulty: 'hard', category: 'Python-Lists',
    question: 'a = [1,2]\nb = a\nb += [3]\nprint(a)',
    options: ['[1,2]', '[1,2,3]', '[3]', 'Error'],
    correctIndex: 1 },
  { id: 'q-h-44', difficulty: 'hard', category: 'Python-Functions',
    question: 'g = (x*x for x in range(3))\nprint(next(g))\nprint(next(g))\nWhat is printed?',
    options: ['0 then 0', '0 then 1', '1 then 4', '1 then 1'],
    correctIndex: 1 },
  { id: 'q-h-45', difficulty: 'hard', category: 'Python-Basics',
    question: 'x = {1,2,2,3,3,3}\nprint(len(x))',
    options: ['3', '4', '5', '6'],
    correctIndex: 0 },
  { id: 'q-h-46', difficulty: 'hard', category: 'Python-Dictionaries',
    question: 'd = {1: "a", True: "b"}\nWhat is len(d)?',
    options: ['0', '1', '2', 'Error'],
    correctIndex: 1 },
  { id: 'q-h-47', difficulty: 'hard', category: 'Python-Scope',
    question: 'x = 10\ndef f():\nx = 20\nreturn x\nprint(f(), x)',
    options: ['10 20', '20 20', '20 10', '10 10'],
    correctIndex: 2 },
  { id: 'q-h-48', difficulty: 'hard', category: 'Python-Loops',
    question: 'for i in range(3):\nif i == 5:\nbreak\nelse:\nprint("DONE")\nWhat is printed?',
    options: ['Nothing', 'DONE', '5', 'Error'],
    correctIndex: 1 },
  { id: 'q-h-49', difficulty: 'hard', category: 'Java-Initialization',
    question: 'class A {\nstatic { System.out.print("S"); }\n{ System.out.print("I"); }\nA() { System.out.print("C"); }\n}\nnew A();\nnew A();\nWhat is printed?',
    options: ['SIC SIC', 'SICSIC', 'SICIC', 'SS IICC'],
    correctIndex: 2 },
  { id: 'q-h-50', difficulty: 'hard', category: 'Java-Polymorphism',
    question: 'void f(long x) { System.out.print("L"); }\nvoid f(double x) { System.out.print("D"); }\nf(5);\nWhich overload is selected?',
    options: ['L', 'D', 'Both', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-h-51', difficulty: 'hard', category: 'Java-Polymorphism',
    question: 'void f(String s) { System.out.print("S"); }\nvoid f(Object o) { System.out.print("O"); }\nf(null);\nWhich method is selected?',
    options: ['S', 'O', 'Both', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-h-52', difficulty: 'hard', category: 'Java-Basics',
    question: 'final int[] a = {1,2};\na[0] = 9;\nWhich statement is correct?',
    options: ['Compilation error because a is final', 'Array contents can change even though the reference cannot be reassigned', 'Both reference and contents become immutable', 'Runtime error'],
    correctIndex: 1 },
  { id: 'q-h-53', difficulty: 'hard', category: 'Java-Basics',
    question: 'String a = new String("CAT");\nString b = new String("CAT");\nWhich is true?',
    options: ['a == b is true', 'a.equals(b) is true', 'Both are false', 'Both are true'],
    correctIndex: 1 },
  { id: 'q-h-54', difficulty: 'hard', category: 'Java-Basics',
    question: 'String s = null;\nSystem.out.println(s instanceof String);\nWhat is printed?',
    options: ['true', 'false', 'null', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-h-55', difficulty: 'hard', category: 'Java-Constructors',
    question: 'class A {\nA() { this(5); }\nA(int x) { System.out.print(x); }\n}\nnew A();\nWhat is printed?',
    options: ['0', '5', 'A5', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-h-56', difficulty: 'hard', category: 'Java-OOP',
    question: 'abstract class A {\nabstract void show();\n}\nCan A be instantiated directly with new A()?',
    options: ['Yes', 'No', 'Only if show() is static', 'Only inside A'],
    correctIndex: 1 },
  { id: 'q-h-57', difficulty: 'hard', category: 'Java-OOP',
    question: 'interface I {\nvoid show();\n}\nclass A implements I {\npublic void show() { System.out.print("A"); }\n}\nI x = new A();\nx.show();\nWhat is printed?',
    options: ['I', 'A', 'Nothing', 'Compilation error'],
    correctIndex: 1 },
  { id: 'q-h-58', difficulty: 'hard', category: 'Java-Inheritance',
    question: 'class A {\nprotected void show() {}\n}\nclass B extends A {\npublic void show() {}\n}\nWhich statement is correct?',
    options: ['Invalid because visibility cannot change', 'Valid because overriding can widen access', 'Invalid because public is narrower', 'Valid only if show is static'],
    correctIndex: 1 },
  { id: 'q-h-59', difficulty: 'hard', category: 'Java-Basics',
    question: 'try {\nint[] a = new int[2];\nSystem.out.println(a[3]);\n} catch (ArrayIndexOutOfBoundsException e) {\nSystem.out.print("X");\n}\nWhat is printed?',
    options: ['X', '3', '0', 'Compilation error'],
    correctIndex: 0 },
  { id: 'q-h-60', difficulty: 'hard', category: 'Java-Polymorphism',
    question: 'class A {\nObject get() { return new Object(); }\n}\nclass B extends A {\nString get() { return "OK"; }\n}\nIs B.get() a valid override?',
    options: ['No, return types must always be identical', 'Yes, String is a subtype of Object', 'Only if get() is static', 'Only if Object is final'],
    correctIndex: 1 }
]
